// <auto-generated />
namespace Bakery_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddDriver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDriver));
        
        string IMigrationMetadata.Id
        {
            get { return "202210241234172_Add-Driver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
