// <auto-generated />
namespace Bakery_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderAddConfirmDelivery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderAddConfirmDelivery));
        
        string IMigrationMetadata.Id
        {
            get { return "202210250533006_Order-Add-Confirm-Delivery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
